import { Client } from 'pg';

const connectionString = 'postgresql://postgres:##Ekeepa1402@db.crqxptyndqftcczeioue.supabase.co:5432/postgres';

export const runQuery = async (query: string, params: any[] = []) => {
    const client = new Client({
        connectionString,
    });

    try {
        await client.connect();
        console.log('Connected to Supabase DB successfully.');

        const res = await client.query(query, params);
        console.log('Query result:', res.rows);
        return res.rows;
    } catch (err) {
        console.error('Database error:', err);
        throw err;
    } finally {
        await client.end();
    }
};

// Example: Create the users table if it doesn't exist (Schema Migration)
export const initDb = async () => {
    const createTableQuery = `
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      phone_number TEXT NOT NULL,
      persona_type TEXT,
      persona_title TEXT,
      stats JSONB
    );
  `;

    console.log('Initializing Database...');
    await runQuery(createTableQuery);
    console.log('Database initialized.');
};

// Uncomment to run initialization
// initDb();
